theme: jekyll-theme-cayman
title: Klepsydra Community
description: An open source framework for high performance edge data processing.
github:
  repository_core_url: https://github.com/klepsydra-technologies/kpsr-core
  repository_robo_url: https://github.com/klepsydra-technologies/kpsr-robotics
  repository_tuto_url: https://github.com/klepsydra-technologies/kpsr-tutorial
  repository_visi_url: https://github.com/klepsydra-technologies/kpsr-vision-ocv-tutorial

# Analytics
analytics:
  provider: google-gtag
  google:
    measurement_id: G-V11CG5BFH1
    anonymize_ip: false
